"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const react_redux_1 = require("react-redux");
const React = require("react");
const icons_1 = require("../../components/icons");
const actions = require("../../reducers/main/actions");
require("../../static/scss/routes/main.scss");
class Main extends React.Component {
    componentDidMount() {
        this.props.addId();
    }
    render() {
        const { mainmodel } = this.props;
        console.log('mainmodel', mainmodel);
        return (React.createElement("div", { className: "front" },
            React.createElement("div", { className: "front_header" },
                React.createElement("div", { className: "front_content front_header_content" },
                    React.createElement("div", { className: "front_header_top" },
                        React.createElement("a", { className: "logo_link", href: "/" },
                            React.createElement("img", { className: "logo_img", src: require('../../static/media/poweredbyhss_light.svg'), alt: "Partners Portal Logo", width: "auto", height: "50" })),
                        React.createElement("ul", { className: "menu" },
                            React.createElement("li", { className: "menu_item docslink" },
                                React.createElement("span", { className: "menu_link" },
                                    React.createElement(icons_1.IconHTMLTag, { width: "24", height: "24" }),
                                    React.createElement("span", null, "Docs")),
                                React.createElement("div", { className: "docslink_drop" },
                                    React.createElement("ul", { className: "docslink_list" },
                                        React.createElement("li", { className: "docslink_item" },
                                            React.createElement("a", { className: "docslink_link", href: "/docs/proxy_sdk_android.html", target: "_blank" }, "Proxy SDK for Android")),
                                        React.createElement("li", { className: "docslink_item" },
                                            React.createElement("a", { className: "docslink_link", href: "/docs/proxy_sdk_ios.html", target: "_blank" }, "Proxy SDK for iOS")),
                                        React.createElement("li", { className: "docslink_item" },
                                            React.createElement("a", { className: "docslink_link", href: "/docs/vpn_sdk_android_openvpn.html", target: "_blank" }, "VPN SDK for Android (OpenVPN)")),
                                        React.createElement("li", { className: "docslink_item" },
                                            React.createElement("a", { className: "docslink_link", href: "/docs/vpn_sdk_ios_ipsec.html", target: "_blank" }, "VPN SDK for iOS (IPsec)")),
                                        React.createElement("li", { className: "docslink_item" },
                                            React.createElement("a", { className: "docslink_link", href: "http://backend.northghost.com/doc/partner/index.html", target: "_blank" }, "Partner API")),
                                        React.createElement("li", { className: "docslink_item" },
                                            React.createElement("a", { className: "docslink_link", href: "https://backend.northghost.com/doc/user/index.html", target: "_blank" }, "User API"))))),
                            React.createElement("li", { className: "menu_item" },
                                React.createElement("a", { className: "menu_link", href: "mailto:platformpartners@anchorfree.com" },
                                    React.createElement(icons_1.IconQuestion, { width: "17", height: "17" }),
                                    React.createElement("span", null, "Help")))),
                        React.createElement("ul", { className: "auth" },
                            React.createElement("li", { className: "auth_item" },
                                React.createElement("a", { className: "auth_link auth_link-active", href: "/auth/signup" }, "Sign up")),
                            React.createElement("li", { className: "auth_item" },
                                React.createElement("a", { className: "auth_link", href: "/auth/signin" }, "Sign in")))),
                    React.createElement("div", { className: "front_header_middle" },
                        React.createElement("h1", null, "Freedom as a Service"),
                        React.createElement("p", null,
                            "Build secure apps that can't be",
                            React.createElement("br", null),
                            "throttled or restricted"),
                        React.createElement("ul", { className: "selllinks" },
                            React.createElement("li", { className: "selllinks_item" },
                                React.createElement("a", { className: "selllinks_item_link selllinks_item_link-custom", href: "/auth/signup" }, "Get a FREE API key")),
                            React.createElement("li", { className: "selllinks_item" },
                                React.createElement("a", { className: "selllinks_item_link selllinks_item_link-simple", href: "mailto:platformpartners@anchorfree.com" }, "Learn more")))))),
            React.createElement("div", { className: "front_products" },
                React.createElement("div", { className: "front_content" },
                    React.createElement("h2", { className: "front_content_header" },
                        React.createElement("span", { className: "front_products_header" }, "Products")),
                    React.createElement("ul", { className: "front_products_list" },
                        React.createElement("li", { className: "front_products_item" },
                            React.createElement("div", { className: "front_products_img front_products_img-1" }),
                            React.createElement("p", { className: "front_products_promo" }, "Keep Your Users Safe"),
                            React.createElement("p", { className: "front_products_promo-big" }, "VPN SDK"),
                            React.createElement("p", { className: "front_products_description" }, "Enable a VPN for securing the entire operating system of your users. Protects your user data from malicious websites, ISPs, and hackers. Protects from unsafe networks (like public Wi-Fi). Puts you in control of the enter OS."),
                            React.createElement("a", { href: "/auth/signup", className: "front_products_action" }, "Try it now")),
                        React.createElement("li", { className: "front_products_item" },
                            React.createElement("div", { className: "front_products_img front_products_img-2" }),
                            React.createElement("p", { className: "front_products_promo" }, "Make Your App Unstoppable"),
                            React.createElement("p", { className: "front_products_promo-big" }, "Proxy SDK"),
                            React.createElement("p", { className: "front_products_description" }, "Protects your app from throttling, censorship, or any kind of interference from Internet Service providers. Protects your user data from ISPs and hackers. Ensures that your app is always available from anywhere in the world."),
                            React.createElement("a", { href: "/auth/signup", className: "front_products_action" }, "Try it now")),
                        React.createElement("li", { className: "front_products_item" },
                            React.createElement("div", { className: "front_products_img front_products_img-3" }),
                            React.createElement("p", { className: "front_products_promo" }, "Secure Your Business Connection"),
                            React.createElement("p", { className: "front_products_promo-big" }, "VPN for business"),
                            React.createElement("p", { className: "front_products_description" }, "Use AnchorFree\u2019s proprietary, lightning-fast Hydra VPN and the AnchorFree Server Network (among the 100 largest networks in the world). Contact our partnership team For more information."),
                            React.createElement("a", { href: "mailto:platformpartners@anchorfree.com", className: "front_products_action" }, "Learn more"))))),
            React.createElement("div", { className: "front_features" },
                React.createElement("div", { className: "front_content" },
                    React.createElement("h2", { className: "front_content_header" },
                        React.createElement("span", null, "FEATURES")),
                    React.createElement("div", { className: "features_pane" },
                        React.createElement("h3", null, "Our key features"),
                        React.createElement("div", { className: "features_content" },
                            React.createElement("img", { className: "features_img", src: require('../../static/media/front_features.png'), alt: "VPN Services by AnchorFree", width: "867", height: "2141" }),
                            React.createElement("div", { className: "features_item features_item-1" },
                                React.createElement("h4", { className: "features_header" }, "Protocols and Platforms"),
                                React.createElement("p", { className: "features_text" }, "We support popular VPN protocols and major client platforms"),
                                React.createElement("p", { className: "features_text" },
                                    "We support popular VPN protocols:",
                                    React.createElement("br", null),
                                    React.createElement("a", { href: "/" }, "OpenVPN"),
                                    ", ",
                                    React.createElement("a", { href: "/" }, "IPSEC"),
                                    ", ",
                                    React.createElement("a", { href: "/" }, "Hydra"),
                                    React.createElement("br", null),
                                    React.createElement("br", null),
                                    "and major client platforms:",
                                    React.createElement("br", null),
                                    React.createElement("a", { href: "/" }, "iOS"),
                                    ", ",
                                    React.createElement("a", { href: "/" }, "OSX"),
                                    ", ",
                                    React.createElement("a", { href: "/" }, "Android"),
                                    ", ",
                                    React.createElement("a", { href: "/" }, "Windows"))),
                            React.createElement("div", { className: "features_item features_item-2" },
                                React.createElement("h4", { className: "features_header" }, "Works out of the \"box\""),
                                React.createElement("p", { className: "features_text" }, "Easy to use in new applications as well as existing apps")),
                            React.createElement("div", { className: "features_item features_item-3" },
                                React.createElement("h4", { className: "features_header" }, "Focus On Accessibility"),
                                React.createElement("p", { className: "features_text" }, "Choose from thousands of server endpoints around the world or the quickest for your users")),
                            React.createElement("div", { className: "features_item features_item-4" },
                                React.createElement("h4", { className: "features_header" }, "We Take Privacy Seriously"),
                                React.createElement("p", { className: "features_text" }, "We do not store, log or monitor individual user data or traffic.")),
                            React.createElement("div", { className: "features_item features_item-5" },
                                React.createElement("h4", { className: "features_header" }, "Simple to Manage"),
                                React.createElement("p", { className: "features_text" }, "Monitor and manage your apps from a single dashboard in your account")),
                            React.createElement("div", { className: "features_circle" },
                                React.createElement("svg", { height: "45", viewBox: "0 0 1792 1792", width: "45", xmlns: "http://www.w3.org/2000/svg" },
                                    React.createElement("path", { d: "M1395 736q0 13-10 23l-466 466q-10 10-23 10t-23-10L407 759q-10-10-10-23t10-23l50-50q10-10 23-10t23 10l393 393 393-393q10-10 23-10t23 10l50 50q10 10 10 23z" }))))))),
            React.createElement("div", { className: "front_getkey getkey" },
                React.createElement("div", { className: "front_content" },
                    React.createElement("div", { className: "getkey_pane" },
                        React.createElement("img", { className: "getkey_pane_img", src: require('../../static/media/front_getkey_img.png'), alt: "", width: "430", height: "430" }),
                        React.createElement("div", { className: "getkey_pane_content" },
                            React.createElement("h2", { className: "getkey_pane_header" }, "Ready to get started?"),
                            React.createElement("div", { className: "getkey_pane_banch" },
                                React.createElement("span", null, "FOR FREE")),
                            React.createElement("a", { href: "/auth/signup", className: "getkey_pane_action" }, "Get a FREE API key"))),
                    React.createElement("div", { className: "getkey_clients" },
                        React.createElement("h2", { className: "front_content_header" },
                            React.createElement("span", { className: "front_getkey_header" }, "Our Partners")),
                        React.createElement("ul", { className: "getkey_clients_list" },
                            React.createElement("li", { className: "getkey_clients_item getkey_clients_item-1" }),
                            React.createElement("li", { className: "getkey_clients_item getkey_clients_item-2" }),
                            React.createElement("li", { className: "getkey_clients_item getkey_clients_item-3" }))))),
            React.createElement("div", { className: "front_footer" },
                React.createElement("div", { className: "front_footer_top" },
                    React.createElement("div", { className: "front_content footer_top" },
                        React.createElement("div", { className: "footer_top_logo" },
                            React.createElement("img", { className: "footer_top_img", src: require('../../static/media/poweredbyhss_dark.svg'), alt: "Partners Portal Logo", width: "auto", height: "40" }),
                            React.createElement("div", { className: "footer_top_copy" }, "Copyright \u00A9 2017 AnchorFree, Inc. All Rights Reserved")),
                        React.createElement("div", { className: "footer_top_menu" },
                            React.createElement("ul", { className: "footer_top_list" },
                                React.createElement("li", { className: "footer_top_item" },
                                    React.createElement("a", { className: "footer_top_link", href: "/" }, "Docs")),
                                React.createElement("li", { className: "footer_top_item" },
                                    React.createElement("a", { className: "footer_top_link", href: "mailto:platformpartners@anchorfree.com" }, "Help")),
                                React.createElement("li", { className: "footer_top_item" },
                                    React.createElement("a", { className: "footer_top_link", href: "/auth/signin" }, "Log in"),
                                    "\u00A0&\u00A0",
                                    React.createElement("a", { className: "footer_top_link", href: "/auth/signup" }, "Sign up")))))))));
    }
}
exports.default = react_redux_1.connect(state => ({
    mainmodel: state.mains
}), ({
    addId: actions.addId
}))(Main);
//# sourceMappingURL=index.js.map