export const LOAD_TRAFFIC = 'LOAD_TRAFFIC';
export const MODIFY_SUBSCRIBER = 'MODIFY_SUBSCRIBER';
export const SET_LIMIT = 'SET_LIMIT';
export const GET_SESSIONS = 'GET_SESSIONS';
export const GET_DEVICES = 'GET_DEVICES';
export const GET_PURCHASES = 'GET_DEVICES';
