export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';
export const SET_ACTIVE_PROJECT = 'SET_ACTIVE_PROJECT';
export const LOAD_SUBSCRIBERS = 'LOAD_SUBSCRIBERS';
export const LOAD_LICENSES = 'LOAD_LICENSES';
export const SEARCH_SUBSCRIBERS = 'SEARCH_SUBSCRIBERS';
export const SET_ACTIVE_SUBSCRIBER = 'SET_ACTIVE_SUBSCRIBER';
export const ADD_SUBSCRIBER = 'ADD_SUBSCRIBER';

