export const LOAD_LICENSES = 'LOAD_LICENSES';
export const LOAD_SUBSCRIBERS = 'LOAD_SUBSCRIBERS';
export const SEARCH_SUBSCRIBERS = 'SEARCH_SUBSCRIBERS';
export const ADD_SUBSCRIBER = 'ADD_SUBSCRIBER';
export const SET_ACTIVE_PROJECT = 'SET_ACTIVE_PROJECT';
