export default {
	host: 'http://vpn-backend.northghost.com/',
	firebaseToken: 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImY3ZGFjOGY4MzYwNjVjODgwODNkMzkwNzZhODU4OWEzMTk5NWZjNDQifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vd2ViLXBvcnRhbC1mb3ItcGFydG5lcnMiLCJhdWQiOiJ3ZWItcG9ydGFsLWZvci1wYXJ0bmVycyIsImF1dGhfdGltZSI6MTUwMzU5MTA0OCwidXNlcl9pZCI6IjhmOHJFZ0tSM3ZSNzVaSWtlNUJ3aXBReUNIeTEiLCJzdWIiOiI4ZjhyRWdLUjN2Ujc1WklrZTVCd2lwUXlDSHkxIiwiaWF0IjoxNTAzNTkxMDQ4LCJleHAiOjE1MDM1OTQ2NDgsImVtYWlsIjoiMHh5OWVuQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIjB4eTllbkBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.coEjsVzcidPMd_WHogfwExH44rxWZA5p3ldZFVVKfXIaQae1SOjhYYz9pEVt-PIZhi3KZbeFhMYeY7fijch_tLilFYQ0SK_OFgfzB7SGeEKbMOYap6ilbFDaIpkr-1kqEdJPZ1gCv8U4RtbWpVa1qCaCmtHPTsYNlONnyUaURISUVGzRoDohDnwLXqYDp721YuN-HMXpq7JRhMXOKom3Uehhjfd17dgIHgoZAsdZzhc4n3vMBur32EVG-hl1JkL2Ll34v70yL3e1KeecULNsVkSiKJmRBYa7kol6zRXJxU9O35Okqf245PtNz2w8v0zU9eLMIneX8U74x5HgDY5LQA',
	firebaseKey: ' AIzaSyBjJGXAQW9wuT7O1_bHMoLPaT6YSM1ELGU',
	firebaseAuthDomain: 'web-portal-for-partners.firebaseapp.com',
	firebasedatabaseURL: 'https://web-portal-for-partners.firebaseio.com'
};