export default {
	host: 'http://vpn-backend.northghost.com/',
	firebaseToken: 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImY3ZGFjOGY4MzYwNjVjODgwODNkMzkwNzZhODU4OWEzMTk5NWZjNDQifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vd2ViLXBvcnRhbC1mb3ItcGFydG5lcnMiLCJhdWQiOiJ3ZWItcG9ydGFsLWZvci1wYXJ0bmVycyIsImF1dGhfdGltZSI6MTUwMzU4NzAzNywidXNlcl9pZCI6IjhmOHJFZ0tSM3ZSNzVaSWtlNUJ3aXBReUNIeTEiLCJzdWIiOiI4ZjhyRWdLUjN2Ujc1WklrZTVCd2lwUXlDSHkxIiwiaWF0IjoxNTAzNTkwNzUyLCJleHAiOjE1MDM1OTQzNTIsImVtYWlsIjoiMHh5OWVuQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIjB4eTllbkBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.Ui5vDbVOWRqiv_GXz2T7Rawt6b3Gm-lToYQaiN8MYkdjXoAtodeDmYdrwOMpJLHSY54_L_bFS4lzcWQJYCu5u1JqulC6TtA8J0ZY2sv115I8tO31bzWHjL7PAVefDKW4UZY95kOPfRKKqFU0KCXDdehVrwMMn4HgV4fuAPOhWIZlvuVhgc46W3ZVVf7cwPmfa3gQCVnd4EAB6Y5HVf1ddgkpUW5k6xeNjHI4bhcPBYkc1DgIShxIjZoEsXOPLGhBOI-5iNPMLVfgx75cwI6VLmOYQBZB2DQ5KkRzUXIXAlbNSvI4h-rJoSucL0KSnfA0lAblh3bYi9WHqec_XND47Q',
	firebaseKey: ' AIzaSyBjJGXAQW9wuT7O1_bHMoLPaT6YSM1ELGU',
	firebaseAuthDomain: 'web-portal-for-partners.firebaseapp.com',
	firebasedatabaseURL: 'https://web-portal-for-partners.firebaseio.com'
};