export default {
	host: 'http://vpn-backend.northghost.com/',
	firebaseToken: 'eyJhbGciOiJSUzI1NiIsImtpZCI6ImY3ZGFjOGY4MzYwNjVjODgwODNkMzkwNzZhODU4OWEzMTk5NWZjNDQifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vd2ViLXBvcnRhbC1mb3ItcGFydG5lcnMiLCJhdWQiOiJ3ZWItcG9ydGFsLWZvci1wYXJ0bmVycyIsImF1dGhfdGltZSI6MTUwMzU1MTQ4MiwidXNlcl9pZCI6IjhmOHJFZ0tSM3ZSNzVaSWtlNUJ3aXBReUNIeTEiLCJzdWIiOiI4ZjhyRWdLUjN2Ujc1WklrZTVCd2lwUXlDSHkxIiwiaWF0IjoxNTAzNTU1NTMyLCJleHAiOjE1MDM1NTkxMzIsImVtYWlsIjoiMHh5OWVuQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbIjB4eTllbkBnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.VM1iVYX1WZuXAqoAgzTeDbNPv9KmCxqc029-lZEMp7MlK0i2r1UejXi0ZbdEbMRhVIUQ_mgyjGX1C3VgU3U1T21W7OZbiA4ledBNjJ1AOKvJbgo3_D_uBTCGJIEQndYw75kxG5VQxWLHz-V58WsvqPIWwvjyWIlWBK1T4m5uyNEPD35MJieEElzsxCpw0tsk-WFGNYhg1tGiwUuVhkYP_XJMK2wVanYgpbn4DT9gSnpV87-TBRKzeDqSPjsON74lUGIs888XCBzspyyCmRIrNKcoCbO1Lq3vnt8Wj7mTfs4NwlliYyC7aVMD75zu-Gt1NZIud22-ZUSEX5I20xgvtA',
	firebaseKey: ' AIzaSyBjJGXAQW9wuT7O1_bHMoLPaT6YSM1ELGU',
	firebaseAuthDomain: 'web-portal-for-partners.firebaseapp.com',
	firebasedatabaseURL: 'https://web-portal-for-partners.firebaseio.com'
};